### ISSUE TITLE
Extension currently down because of Insight server no longer available. 

### ISSUE THREAD

**Issue by auroracoin101** [auroracoin101/auroracoin-browser-wallet#2]
All funds are safe and tied to your private key stored locally on your machine.

**Comment by SkateFish** [comment]
December 2022 Update.  We have migrated the code to use Electrum SPV servers instead of Insight Server. 
Final testing underway.

**Comment by auroracoin101** [comment]
Version 2.10.0 released on Google Web Store. https://chrome.google.com/webstore/detail/auroracoin-browser-wallet/ibbbddhliiimfdpadncmdnbhgagplagk?hl=en&authuser=0

All functionality restored.  Added transaction_id link when sending coins. Some UI changes
